/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated/recipes/index'
import { Route as AuthenticatedPantryIndexRouteImport } from './routes/_authenticated/pantry/index'
import { Route as AuthenticatedGroceryListsIndexRouteImport } from './routes/_authenticated/grocery-lists/index'
import { Route as AuthenticatedRecipesNewRouteImport } from './routes/_authenticated/recipes/new'
import { Route as AuthenticatedRecipesImportRouteImport } from './routes/_authenticated/recipes/import'
import { Route as AuthenticatedRecipesRecipeIdRouteImport } from './routes/_authenticated/recipes/$recipeId'
import { Route as AuthenticatedPantryNewRouteImport } from './routes/_authenticated/pantry/new'
import { Route as AuthenticatedPantryPantryItemIdRouteImport } from './routes/_authenticated/pantry/$pantryItemId'
import { Route as AuthenticatedGroceryListsGroceryListIdRouteImport } from './routes/_authenticated/grocery-lists/$groceryListId'
import { Route as AuthenticatedRecipesRecipeIdEditRouteImport } from './routes/_authenticated/recipes/$recipeId_.edit'
import { Route as AuthenticatedPantryPantryItemIdEditRouteImport } from './routes/_authenticated/pantry/$pantryItemId_.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPantryIndexRoute =
  AuthenticatedPantryIndexRouteImport.update({
    id: '/pantry/',
    path: '/pantry/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroceryListsIndexRoute =
  AuthenticatedGroceryListsIndexRouteImport.update({
    id: '/grocery-lists/',
    path: '/grocery-lists/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesNewRoute = AuthenticatedRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesImportRoute =
  AuthenticatedRecipesImportRouteImport.update({
    id: '/recipes/import',
    path: '/recipes/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesRecipeIdRoute =
  AuthenticatedRecipesRecipeIdRouteImport.update({
    id: '/recipes/$recipeId',
    path: '/recipes/$recipeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPantryNewRoute = AuthenticatedPantryNewRouteImport.update({
  id: '/pantry/new',
  path: '/pantry/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPantryPantryItemIdRoute =
  AuthenticatedPantryPantryItemIdRouteImport.update({
    id: '/pantry/$pantryItemId',
    path: '/pantry/$pantryItemId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroceryListsGroceryListIdRoute =
  AuthenticatedGroceryListsGroceryListIdRouteImport.update({
    id: '/grocery-lists/$groceryListId',
    path: '/grocery-lists/$groceryListId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesRecipeIdEditRoute =
  AuthenticatedRecipesRecipeIdEditRouteImport.update({
    id: '/recipes/$recipeId_/edit',
    path: '/recipes/$recipeId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPantryPantryItemIdEditRoute =
  AuthenticatedPantryPantryItemIdEditRouteImport.update({
    id: '/pantry/$pantryItemId_/edit',
    path: '/pantry/$pantryItemId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-email': typeof CheckEmailRoute
  '/confirm': typeof ConfirmRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grocery-lists/$groceryListId': typeof AuthenticatedGroceryListsGroceryListIdRoute
  '/pantry/$pantryItemId': typeof AuthenticatedPantryPantryItemIdRoute
  '/pantry/new': typeof AuthenticatedPantryNewRoute
  '/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRoute
  '/recipes/import': typeof AuthenticatedRecipesImportRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/grocery-lists/': typeof AuthenticatedGroceryListsIndexRoute
  '/pantry/': typeof AuthenticatedPantryIndexRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/pantry/$pantryItemId/edit': typeof AuthenticatedPantryPantryItemIdEditRoute
  '/recipes/$recipeId/edit': typeof AuthenticatedRecipesRecipeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-email': typeof CheckEmailRoute
  '/confirm': typeof ConfirmRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grocery-lists/$groceryListId': typeof AuthenticatedGroceryListsGroceryListIdRoute
  '/pantry/$pantryItemId': typeof AuthenticatedPantryPantryItemIdRoute
  '/pantry/new': typeof AuthenticatedPantryNewRoute
  '/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRoute
  '/recipes/import': typeof AuthenticatedRecipesImportRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/grocery-lists': typeof AuthenticatedGroceryListsIndexRoute
  '/pantry': typeof AuthenticatedPantryIndexRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
  '/pantry/$pantryItemId/edit': typeof AuthenticatedPantryPantryItemIdEditRoute
  '/recipes/$recipeId/edit': typeof AuthenticatedRecipesRecipeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/confirm': typeof ConfirmRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/grocery-lists/$groceryListId': typeof AuthenticatedGroceryListsGroceryListIdRoute
  '/_authenticated/pantry/$pantryItemId': typeof AuthenticatedPantryPantryItemIdRoute
  '/_authenticated/pantry/new': typeof AuthenticatedPantryNewRoute
  '/_authenticated/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRoute
  '/_authenticated/recipes/import': typeof AuthenticatedRecipesImportRoute
  '/_authenticated/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/_authenticated/grocery-lists/': typeof AuthenticatedGroceryListsIndexRoute
  '/_authenticated/pantry/': typeof AuthenticatedPantryIndexRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/_authenticated/pantry/$pantryItemId_/edit': typeof AuthenticatedPantryPantryItemIdEditRoute
  '/_authenticated/recipes/$recipeId_/edit': typeof AuthenticatedRecipesRecipeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-email'
    | '/confirm'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/grocery-lists/$groceryListId'
    | '/pantry/$pantryItemId'
    | '/pantry/new'
    | '/recipes/$recipeId'
    | '/recipes/import'
    | '/recipes/new'
    | '/grocery-lists/'
    | '/pantry/'
    | '/recipes/'
    | '/pantry/$pantryItemId/edit'
    | '/recipes/$recipeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-email'
    | '/confirm'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/grocery-lists/$groceryListId'
    | '/pantry/$pantryItemId'
    | '/pantry/new'
    | '/recipes/$recipeId'
    | '/recipes/import'
    | '/recipes/new'
    | '/grocery-lists'
    | '/pantry'
    | '/recipes'
    | '/pantry/$pantryItemId/edit'
    | '/recipes/$recipeId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/check-email'
    | '/confirm'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/grocery-lists/$groceryListId'
    | '/_authenticated/pantry/$pantryItemId'
    | '/_authenticated/pantry/new'
    | '/_authenticated/recipes/$recipeId'
    | '/_authenticated/recipes/import'
    | '/_authenticated/recipes/new'
    | '/_authenticated/grocery-lists/'
    | '/_authenticated/pantry/'
    | '/_authenticated/recipes/'
    | '/_authenticated/pantry/$pantryItemId_/edit'
    | '/_authenticated/recipes/$recipeId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CheckEmailRoute: typeof CheckEmailRoute
  ConfirmRoute: typeof ConfirmRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pantry/': {
      id: '/_authenticated/pantry/'
      path: '/pantry'
      fullPath: '/pantry/'
      preLoaderRoute: typeof AuthenticatedPantryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grocery-lists/': {
      id: '/_authenticated/grocery-lists/'
      path: '/grocery-lists'
      fullPath: '/grocery-lists/'
      preLoaderRoute: typeof AuthenticatedGroceryListsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/new': {
      id: '/_authenticated/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AuthenticatedRecipesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/import': {
      id: '/_authenticated/recipes/import'
      path: '/recipes/import'
      fullPath: '/recipes/import'
      preLoaderRoute: typeof AuthenticatedRecipesImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/$recipeId': {
      id: '/_authenticated/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof AuthenticatedRecipesRecipeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pantry/new': {
      id: '/_authenticated/pantry/new'
      path: '/pantry/new'
      fullPath: '/pantry/new'
      preLoaderRoute: typeof AuthenticatedPantryNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pantry/$pantryItemId': {
      id: '/_authenticated/pantry/$pantryItemId'
      path: '/pantry/$pantryItemId'
      fullPath: '/pantry/$pantryItemId'
      preLoaderRoute: typeof AuthenticatedPantryPantryItemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grocery-lists/$groceryListId': {
      id: '/_authenticated/grocery-lists/$groceryListId'
      path: '/grocery-lists/$groceryListId'
      fullPath: '/grocery-lists/$groceryListId'
      preLoaderRoute: typeof AuthenticatedGroceryListsGroceryListIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/$recipeId_/edit': {
      id: '/_authenticated/recipes/$recipeId_/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof AuthenticatedRecipesRecipeIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pantry/$pantryItemId_/edit': {
      id: '/_authenticated/pantry/$pantryItemId_/edit'
      path: '/pantry/$pantryItemId/edit'
      fullPath: '/pantry/$pantryItemId/edit'
      preLoaderRoute: typeof AuthenticatedPantryPantryItemIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGroceryListsGroceryListIdRoute: typeof AuthenticatedGroceryListsGroceryListIdRoute
  AuthenticatedPantryPantryItemIdRoute: typeof AuthenticatedPantryPantryItemIdRoute
  AuthenticatedPantryNewRoute: typeof AuthenticatedPantryNewRoute
  AuthenticatedRecipesRecipeIdRoute: typeof AuthenticatedRecipesRecipeIdRoute
  AuthenticatedRecipesImportRoute: typeof AuthenticatedRecipesImportRoute
  AuthenticatedRecipesNewRoute: typeof AuthenticatedRecipesNewRoute
  AuthenticatedGroceryListsIndexRoute: typeof AuthenticatedGroceryListsIndexRoute
  AuthenticatedPantryIndexRoute: typeof AuthenticatedPantryIndexRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
  AuthenticatedPantryPantryItemIdEditRoute: typeof AuthenticatedPantryPantryItemIdEditRoute
  AuthenticatedRecipesRecipeIdEditRoute: typeof AuthenticatedRecipesRecipeIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGroceryListsGroceryListIdRoute:
    AuthenticatedGroceryListsGroceryListIdRoute,
  AuthenticatedPantryPantryItemIdRoute: AuthenticatedPantryPantryItemIdRoute,
  AuthenticatedPantryNewRoute: AuthenticatedPantryNewRoute,
  AuthenticatedRecipesRecipeIdRoute: AuthenticatedRecipesRecipeIdRoute,
  AuthenticatedRecipesImportRoute: AuthenticatedRecipesImportRoute,
  AuthenticatedRecipesNewRoute: AuthenticatedRecipesNewRoute,
  AuthenticatedGroceryListsIndexRoute: AuthenticatedGroceryListsIndexRoute,
  AuthenticatedPantryIndexRoute: AuthenticatedPantryIndexRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
  AuthenticatedPantryPantryItemIdEditRoute:
    AuthenticatedPantryPantryItemIdEditRoute,
  AuthenticatedRecipesRecipeIdEditRoute: AuthenticatedRecipesRecipeIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CheckEmailRoute: CheckEmailRoute,
  ConfirmRoute: ConfirmRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
