/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedRecipesIndexRouteImport } from './routes/_protected/recipes/index'
import { Route as ProtectedPantryIndexRouteImport } from './routes/_protected/pantry/index'
import { Route as ProtectedGroceryListsIndexRouteImport } from './routes/_protected/grocery-lists/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRecipesIndexRoute = ProtectedRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPantryIndexRoute = ProtectedPantryIndexRouteImport.update({
  id: '/pantry/',
  path: '/pantry/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedGroceryListsIndexRoute =
  ProtectedGroceryListsIndexRouteImport.update({
    id: '/grocery-lists/',
    path: '/grocery-lists/',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/grocery-lists/': typeof ProtectedGroceryListsIndexRoute
  '/pantry/': typeof ProtectedPantryIndexRoute
  '/recipes/': typeof ProtectedRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/grocery-lists': typeof ProtectedGroceryListsIndexRoute
  '/pantry': typeof ProtectedPantryIndexRoute
  '/recipes': typeof ProtectedRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/grocery-lists/': typeof ProtectedGroceryListsIndexRoute
  '/_protected/pantry/': typeof ProtectedPantryIndexRoute
  '/_protected/recipes/': typeof ProtectedRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/grocery-lists/'
    | '/pantry/'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/grocery-lists'
    | '/pantry'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/signup'
    | '/_protected/dashboard'
    | '/_protected/grocery-lists/'
    | '/_protected/pantry/'
    | '/_protected/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/recipes/': {
      id: '/_protected/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof ProtectedRecipesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pantry/': {
      id: '/_protected/pantry/'
      path: '/pantry'
      fullPath: '/pantry/'
      preLoaderRoute: typeof ProtectedPantryIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/grocery-lists/': {
      id: '/_protected/grocery-lists/'
      path: '/grocery-lists'
      fullPath: '/grocery-lists/'
      preLoaderRoute: typeof ProtectedGroceryListsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedGroceryListsIndexRoute: typeof ProtectedGroceryListsIndexRoute
  ProtectedPantryIndexRoute: typeof ProtectedPantryIndexRoute
  ProtectedRecipesIndexRoute: typeof ProtectedRecipesIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedGroceryListsIndexRoute: ProtectedGroceryListsIndexRoute,
  ProtectedPantryIndexRoute: ProtectedPantryIndexRoute,
  ProtectedRecipesIndexRoute: ProtectedRecipesIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
