/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated/recipes/index'
import { Route as AuthenticatedPantryIndexRouteImport } from './routes/_authenticated/pantry/index'
import { Route as AuthenticatedGroceryListsIndexRouteImport } from './routes/_authenticated/grocery-lists/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPantryIndexRoute =
  AuthenticatedPantryIndexRouteImport.update({
    id: '/pantry/',
    path: '/pantry/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroceryListsIndexRoute =
  AuthenticatedGroceryListsIndexRouteImport.update({
    id: '/grocery-lists/',
    path: '/grocery-lists/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-email': typeof CheckEmailRoute
  '/confirm': typeof ConfirmRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grocery-lists/': typeof AuthenticatedGroceryListsIndexRoute
  '/pantry/': typeof AuthenticatedPantryIndexRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-email': typeof CheckEmailRoute
  '/confirm': typeof ConfirmRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grocery-lists': typeof AuthenticatedGroceryListsIndexRoute
  '/pantry': typeof AuthenticatedPantryIndexRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/confirm': typeof ConfirmRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/grocery-lists/': typeof AuthenticatedGroceryListsIndexRoute
  '/_authenticated/pantry/': typeof AuthenticatedPantryIndexRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-email'
    | '/confirm'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/grocery-lists/'
    | '/pantry/'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-email'
    | '/confirm'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/grocery-lists'
    | '/pantry'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/check-email'
    | '/confirm'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/grocery-lists/'
    | '/_authenticated/pantry/'
    | '/_authenticated/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CheckEmailRoute: typeof CheckEmailRoute
  ConfirmRoute: typeof ConfirmRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pantry/': {
      id: '/_authenticated/pantry/'
      path: '/pantry'
      fullPath: '/pantry/'
      preLoaderRoute: typeof AuthenticatedPantryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grocery-lists/': {
      id: '/_authenticated/grocery-lists/'
      path: '/grocery-lists'
      fullPath: '/grocery-lists/'
      preLoaderRoute: typeof AuthenticatedGroceryListsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGroceryListsIndexRoute: typeof AuthenticatedGroceryListsIndexRoute
  AuthenticatedPantryIndexRoute: typeof AuthenticatedPantryIndexRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGroceryListsIndexRoute: AuthenticatedGroceryListsIndexRoute,
  AuthenticatedPantryIndexRoute: AuthenticatedPantryIndexRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CheckEmailRoute: CheckEmailRoute,
  ConfirmRoute: ConfirmRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
